spring.application.name=SmartCampus

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://withmalwijesiri:12345ometh@cluster0.yb9sm.mongodb.net/SmartCampus?retryWrites=true&w=majority

server.port=8080

# Logging
logging.level.org.springframework.boot=INFO
logging.level.org.mongodb.driver=INFO